# Generated by Django 6.0.5 on 2026-08-18 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CUSTOMER_EMAIL', 'Customer Email'), ('INTERNAL_EMAIL', 'Internal Email'), ('WHATSAPP_ADMIN_1', 'WhatsApp Admin 1'), ('WHATSAPP_ADMIN_2', 'WhatsApp Admin 2'), ('WHATSAPP_RECEPTION', 'WhatsApp Reception')], max_length=30)),
                ('recipient', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='core.order')),
            ],
            options={
                'db_table': 'ctf_notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
