# Generated by Django 6.0.5 on 2026-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Payment Phone Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='share_bill',
            field=models.BooleanField(default=False, verbose_name='Share Bill'),
        ),
        migrations.AddField(
            model_name='order',
            name='share_payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'Halopesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash / Taslimu'), ('other', 'Nyingine')], max_length=20, verbose_name='Share Payment Method'),
        ),
        migrations.AddField(
            model_name='order',
            name='share_payment_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Share Payment Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'Halopesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash / Taslimu'), ('other', 'Nyingine')], default='mpesa', max_length=20),
        ),
    ]
