# Generated by Django 6.0.5 on 2026-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_phone_order_share_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='v_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Vue app food id'),
        ),
    ]
