# Generated by Django 6.0.5 on 2026-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_food_v_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
