# Generated by Django 6.0.5 on 2026-08-29 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_food_icon_alter_food_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Handling staff (reception / accountant)'),
        ),
    ]
