# Generated by Django 6.0.5 on 2026-08-29 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant / Mhasibu'), ('staff', 'Staff / Mfanyakazi'), ('receptionist', 'Receptionist / Msaidizi'), ('price_manager', 'Price Manager / Msimamizi wa Bei')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('general', 'General / Jumla'), ('stock', 'Stock / Malighafi'), ('utilities', 'Utilities / Umeme & Maji'), ('marketing', 'Marketing / Utangazaji'), ('salary', 'Salaries / Mishahara'), ('maintenance', 'Maintenance / Matengenezo'), ('other', 'Other / Nyingine')], default='general', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ctf_expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
